# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'QuickHAC' do

pod 'AFNetworking', '~> 2.5'
pod 'KCOrderedAccessorFix', '~> 0.0'
pod 'LTHPasscodeViewController', '~> 3.6'
pod 'Lockbox', '~> 2.1'
pod 'PKRevealController', '~> 2.0'
pod 'QuickDialog', '~> 1.0'
pod 'WYPopoverController', '~> 0.3'
pod 'KVNProgress', '~> 2.1'
pod 'CocoaLumberjack', '2.0.0-rc'
pod 'PLCrashReporter', '1.2-rc5'

end


